# readthedocs.yml

version: 2

build:
  image: latest

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

conda:
  environment: docs/requirements.yaml
